title: Vladimir Zhukov
description: Portfolio
baseurl: "/experience" # не трогай если в корне
url: ""     # не трогай если в Pages
collections:
  cases:
    output: true
  petprojects:
    output: true
    permalink: /pet/:name/
